export const FETCH_WEATHER_INFORMATION_START =
  "FETCH_WEATHER_INFORMATION_START";
export const FETCH_WEATHER_INFORMATION_SUCCESS =
  "FETCH_WEATHER_INFORMATION_SUCCESS";
export const FETCH_WEATHER_INFORMATION_FAILURE =
  "FETCH_WEATHER_INFORMATION_FAILURE";
